packages:
  - 'packages/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - eslint-plugin-barrel-boundary@1.1.1
  - '@turbo/darwin-64@2.10.11'
  - '@turbo/darwin-arm64@2.10.11'
  - '@turbo/linux-64@2.10.11'
  - '@turbo/linux-arm64@2.10.11'
  - '@turbo/windows-64@2.10.11'
  - '@turbo/windows-arm64@2.10.11'
  - turbo@2.10.11
