export enum ExecutionContextErrorCodes {
  INVALID_ATTRIBUTE_VALUE = 'INVALID_ATTRIBUTE_VALUE',
  INVALID_BLANK_CORRELATION_ID = 'INVALID_BLANK_CORRELATION_ID',
  INVALID_BLANK_REQUEST_ID = 'INVALID_BLANK_REQUEST_ID',
  INVALID_CONTEXT_ATTRIBUTES = 'INVALID_CONTEXT_ATTRIBUTES',
  INVALID_STRING_TYPE = 'INVALID_STRING_TYPE',
  MISSING_CONTEXT_ATTRIBUTE = 'MISSING_CONTEXT_ATTRIBUTE',
  NO_ACTIVE_CONTEXT = 'NO_ACTIVE_CONTEXT',
  CONTEXT_MANAGER_REGISTRATION_FAILED = 'CONTEXT_MANAGER_REGISTRATION_FAILED',
}
