export enum ExecutionContextErrorCodes {
  INVALID_BLANK_CORRELATION_ID = 'INVALID_BLANK_CORRELATION_ID',
  INVALID_BLANK_REQUEST_ID = 'INVALID_BLANK_REQUEST_ID',
  NO_ACTIVE_CONTEXT = 'NO_ACTIVE_CONTEXT',
}
